#SqLite. As versões 3.8.0 e superiores são suportadas.
#   gem install sqlite3
#
#   Certifique-se de que a gem SQLite 3 esteja definida em seu Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

#O banco de dados definido como "teste" será apagado e gerando
#novamente a partir do seu banco de dados de desenvolvimento quando
#você execute "rake".
#Não defina este banco de dados como desenvolvimento ou produção.
test:
  adapter: postgresql
  database: myapp_test
  host: localhost
  port: 5432
  username: postgres
  password: bola

production:
  <<: *default
  adapter: postgresql
  database: myapp_production
  host: localhost
  port: 5432
  username: postgres
  password: bola

